# Generated by Django 5.2.17 on 2026-08-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
