# Generated by Django 5.2.17 on 2026-08-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INGENIERO', 'Ingeniero Técnico'), ('AGRICULTOR', 'Agricultor')], default='ADMIN', max_length=20),
        ),
    ]
