# Generated by Django 5.2.17 on 2026-08-07 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('HUMEDAD_SUELO', 'Humedad del suelo'), ('HUMEDAD_AMBIENTE', 'Humedad ambiente'), ('PRESION', 'Presión atmosférica'), ('VIENTO', 'Viento')], max_length=30)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='dispositivos.dispositivo')),
            ],
        ),
    ]
