# Generated by Django 5.2.17 on 2026-08-07 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=250)),
                ('ip_comunicacion', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='ACTIVO', max_length=20)),
                ('ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='parcelas.parcela')),
            ],
        ),
    ]
