# Generated by Django 5.2.17 on 2026-08-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
